# Generated by Django 4.1.3 on 2023-04-12 21:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('avg_cost', models.FloatField()),
                ('category', models.CharField(max_length=20)),
                ('date_released', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='product_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('details', models.TextField()),
                ('date_reviewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itreporting.product')),
            ],
        ),
    ]
